version: "3.8"

services:
  mediawiki:
    image: mediawiki:latest
    ports:
      - "8081:80"
    environment:
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_NAME: my_wiki
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_PASSWORD: wikipass
    depends_on:
      - db
    volumes:
      - mediawiki_data:/var/www/html
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: wikipass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mediawiki_db_data:/var/lib/mysql

volumes:
  mediawiki_data:
  mediawiki_db_data:
