version: "3.8"

services:
  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8082:8080"
    environment:
      ATL_JDBC_URL: jdbc:postgresql://db:5432/jiradb
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jirapass
      ATL_DB_TYPE: postgres72
    depends_on:
      - db
    volumes:
      - jira_home:/var/atlassian/application-data/jira

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jirapass
    volumes:
      - jira_db_data:/var/lib/postgresql/data

volumes:
  jira_home:
  jira_db_data:
